// <auto-generated />
using System;
using KRWebDesign.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KRWebDesign.Migrations
{
    [DbContext(typeof(KRWebDesignContext))]
    [Migration("20181212073708_whFail")]
    partial class whFail
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KRWebDesign.Models.Beef", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Flavor");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductID");

                    b.Property<int>("Quantity");

                    b.Property<string>("TypeOfMeat");

                    b.HasKey("ID");

                    b.ToTable("Beef");
                });

            modelBuilder.Entity("KRWebDesign.Models.Cart", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CartID");

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("ItemID");

                    b.Property<int>("ItemsInToCart");

                    b.Property<string>("OwnerID");

                    b.Property<decimal>("Price");

                    b.Property<int>("ProductID");

                    b.HasKey("ID");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("KRWebDesign.Models.FavoriteSite", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category");

                    b.Property<int?>("FavoriteWebSitesID");

                    b.Property<int>("Rating");

                    b.Property<string>("SiteURL");

                    b.HasKey("ID");

                    b.HasIndex("FavoriteWebSitesID");

                    b.ToTable("FavoriteSite");
                });

            modelBuilder.Entity("KRWebDesign.Models.FavoriteWebSites", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category");

                    b.Property<string>("OwnerID");

                    b.Property<int>("Rating");

                    b.HasKey("ID");

                    b.ToTable("FavoriteWebSites");
                });

            modelBuilder.Entity("KRWebDesign.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<DateTime>("OrderDate");

                    b.Property<string>("Phone");

                    b.Property<string>("PostalCode");

                    b.Property<string>("State");

                    b.Property<decimal>("Total");

                    b.Property<string>("Username");

                    b.HasKey("OrderId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("KRWebDesign.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OrderId");

                    b.Property<int>("ProductId");

                    b.Property<int>("Quantity");

                    b.Property<decimal>("UnitPrice");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("KRWebDesign.Models.PlayerData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthday");

                    b.Property<int>("GamePlaysToDate");

                    b.Property<int>("GamerLevel");

                    b.Property<string>("GamerName");

                    b.Property<DateTime>("LastAttemptedPlay");

                    b.Property<byte>("MembershipTypeId");

                    b.Property<string>("PlayerID");

                    b.Property<int>("TotalGems");

                    b.Property<int>("TriesPerDay");

                    b.HasKey("ID");

                    b.ToTable("PlayerData");
                });

            modelBuilder.Entity("KRWebDesign.Models.Products", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Flavor");

                    b.Property<int>("ItemId");

                    b.Property<string>("OwnerID");

                    b.Property<decimal>("Price");

                    b.HasKey("ID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("KRWebDesign.Models.FavoriteSite", b =>
                {
                    b.HasOne("KRWebDesign.Models.FavoriteWebSites")
                        .WithMany("SiteAddress")
                        .HasForeignKey("FavoriteWebSitesID");
                });

            modelBuilder.Entity("KRWebDesign.Models.OrderDetail", b =>
                {
                    b.HasOne("KRWebDesign.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KRWebDesign.Models.Products", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
